/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as VideoRouteImport } from './routes/video'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ServiceIndexRouteImport } from './routes/service/index'
import { Route as ServiceSlugRouteImport } from './routes/service.$slug'
import { Route as ServiceConsultancyServicesRouteImport } from './routes/service/consultancy-services'
import { Route as ServiceForecastingPredictionsRouteImport } from './routes/service/forecasting-predictions'
import { Route as ServiceSchedulingSoftwareRouteImport } from './routes/service/scheduling-software'
import { Route as ServiceTeamPracticalViewsRouteImport } from './routes/service/team-practical-views'
import { Route as BlogCategoryNameRouteImport } from './routes/blog/category/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceIndexRoute = ServiceIndexRouteImport.update({
  id: '/service/',
  path: '/service/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceConsultancyServicesRoute =
  ServiceConsultancyServicesRouteImport.update({
    id: '/service/consultancy-services',
    path: '/service/consultancy-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceForecastingPredictionsRoute =
  ServiceForecastingPredictionsRouteImport.update({
    id: '/service/forecasting-predictions',
    path: '/service/forecasting-predictions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceSchedulingSoftwareRoute =
  ServiceSchedulingSoftwareRouteImport.update({
    id: '/service/scheduling-software',
    path: '/service/scheduling-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceTeamPracticalViewsRoute =
  ServiceTeamPracticalViewsRouteImport.update({
    id: '/service/team-practical-views',
    path: '/service/team-practical-views',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCategoryNameRoute = BlogCategoryNameRouteImport.update({
  id: '/blog/category/$name',
  path: '/blog/category/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/video': typeof VideoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/service/consultancy-services': typeof ServiceConsultancyServicesRoute
  '/service/forecasting-predictions': typeof ServiceForecastingPredictionsRoute
  '/service/scheduling-software': typeof ServiceSchedulingSoftwareRoute
  '/service/team-practical-views': typeof ServiceTeamPracticalViewsRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/blog/category/$name': typeof BlogCategoryNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/video': typeof VideoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/service/consultancy-services': typeof ServiceConsultancyServicesRoute
  '/service/forecasting-predictions': typeof ServiceForecastingPredictionsRoute
  '/service/scheduling-software': typeof ServiceSchedulingSoftwareRoute
  '/service/team-practical-views': typeof ServiceTeamPracticalViewsRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/service': typeof ServiceIndexRoute
  '/blog/category/$name': typeof BlogCategoryNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/video': typeof VideoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/service/consultancy-services': typeof ServiceConsultancyServicesRoute
  '/service/forecasting-predictions': typeof ServiceForecastingPredictionsRoute
  '/service/scheduling-software': typeof ServiceSchedulingSoftwareRoute
  '/service/team-practical-views': typeof ServiceTeamPracticalViewsRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/blog/category/$name': typeof BlogCategoryNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/video'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/service/$slug'
    | '/service/consultancy-services'
    | '/service/forecasting-predictions'
    | '/service/scheduling-software'
    | '/service/team-practical-views'
    | '/blog/'
    | '/projects/'
    | '/service/'
    | '/blog/category/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/video'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/service/$slug'
    | '/service/consultancy-services'
    | '/service/forecasting-predictions'
    | '/service/scheduling-software'
    | '/service/team-practical-views'
    | '/blog'
    | '/projects'
    | '/service'
    | '/blog/category/$name'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/video'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/service/$slug'
    | '/service/consultancy-services'
    | '/service/forecasting-predictions'
    | '/service/scheduling-software'
    | '/service/team-practical-views'
    | '/blog/'
    | '/projects/'
    | '/service/'
    | '/blog/category/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  VideoRoute: typeof VideoRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
  ServiceConsultancyServicesRoute: typeof ServiceConsultancyServicesRoute
  ServiceForecastingPredictionsRoute: typeof ServiceForecastingPredictionsRoute
  ServiceSchedulingSoftwareRoute: typeof ServiceSchedulingSoftwareRoute
  ServiceTeamPracticalViewsRoute: typeof ServiceTeamPracticalViewsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ServiceIndexRoute: typeof ServiceIndexRoute
  BlogCategoryNameRoute: typeof BlogCategoryNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/': {
      id: '/service/'
      path: '/service'
      fullPath: '/service/'
      preLoaderRoute: typeof ServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$slug': {
      id: '/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/consultancy-services': {
      id: '/service/consultancy-services'
      path: '/service/consultancy-services'
      fullPath: '/service/consultancy-services'
      preLoaderRoute: typeof ServiceConsultancyServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/forecasting-predictions': {
      id: '/service/forecasting-predictions'
      path: '/service/forecasting-predictions'
      fullPath: '/service/forecasting-predictions'
      preLoaderRoute: typeof ServiceForecastingPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/scheduling-software': {
      id: '/service/scheduling-software'
      path: '/service/scheduling-software'
      fullPath: '/service/scheduling-software'
      preLoaderRoute: typeof ServiceSchedulingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/team-practical-views': {
      id: '/service/team-practical-views'
      path: '/service/team-practical-views'
      fullPath: '/service/team-practical-views'
      preLoaderRoute: typeof ServiceTeamPracticalViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$name': {
      id: '/blog/category/$name'
      path: '/blog/category/$name'
      fullPath: '/blog/category/$name'
      preLoaderRoute: typeof BlogCategoryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  VideoRoute: VideoRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ServiceSlugRoute: ServiceSlugRoute,
  ServiceConsultancyServicesRoute: ServiceConsultancyServicesRoute,
  ServiceForecastingPredictionsRoute: ServiceForecastingPredictionsRoute,
  ServiceSchedulingSoftwareRoute: ServiceSchedulingSoftwareRoute,
  ServiceTeamPracticalViewsRoute: ServiceTeamPracticalViewsRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ServiceIndexRoute: ServiceIndexRoute,
  BlogCategoryNameRoute: BlogCategoryNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
